[package]
name = "static-server"
version = "0.0.8"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
description = "Library for serve static files by HTTP"
repository = "https://github.com/DenisKolodin/static-server"
#build = "build.rs"
license = "MIT"

[[bin]]
name = "static-server"
doc = false

[dependencies]
log = "~0.3"
mime_guess = "~1.1"
hyper = "~0.7"
tar = "~0.3"
env_logger = "~0.3"

