[package]
name = "static-server"
version = "0.0.4"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
description = "Library for serve static files by HTTP"
repository = "https://github.com/DenisKolodin/static-server"
build = "build.rs"
license = "MIT"


[dependencies]
mime_guess = "~1.1"
hyper = "~0.6"
tar = "~0.3"
